
/**
 * FileName: StorageQueueEvent.java
 * Assessment: SENG2200 - A3
 * Author: Yosiah de Koeyer
 * Student No: c3329520
 * <p>
 * Description:
 * Class to represent a event generated by a storage queue
 */
public class StorageQueueEvent {
    private final String storageQueueID;      // ID of storage queue event occured in
    private final String itemID;              // ID of item
    private final Type type;                  // Type of event
    private final double time;                // Time event occured

    /**
     * Enumeration to represent the type of event
     */
    enum Type {
        ADD,
        REMOVE,
        ADD_FAILED,
        REMOVE_FAILED,
    }

    /**
     * Constructor when queue ID, item ID, time and type of event is given
     * @param inStorageQueueID ID of storage queue
     * @param inItemID ID of item
     * @param inTime time event occurred
     * @param inType type of event
     */
    public StorageQueueEvent(String inStorageQueueID, String inItemID, Double inTime, Type inType) {
        this.storageQueueID = inStorageQueueID;
        this.itemID = inItemID;
        this.time = inTime;
        this.type = inType;
    }

    /**
     * getID() method
     * @return ID of the queue event occurred in
     */
    public String getID() {
        return this.storageQueueID;
    }

    /**
     * getItemID() method
     * @return ID of the item the event belongs too
     */
    public String getItemID() {
        return this.itemID;
    }

    /**
     * getType() method
     * @return the type of event
     */
    public Type getType() {
        return this.type;
    }

    /**
     * getTime() method
     * @return the time the event occurred
     */
    public double getTime() {
        return time;
    }

    /**
     * toString() method
     * @return String representation of class
     */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("StorageQueueEvent{");
        sb.append("storageQueueID='").append(storageQueueID).append('\'');
        sb.append(", itemID='").append(itemID).append('\'');
        sb.append(", type=").append(type);
        sb.append(", time=").append(time);
        sb.append('}');
        return sb.toString();
    }
}
